MONITORING:
  LOG_LEVEL: INFO

  METRICS:
    TRACK:
      - PORTFOLIO_MAX_LOSS
      - REALIZED_PNL
      - UNREALIZED_PNL
      - NET_DELTA
      - VIX_AT_ENTRY

  ALERTS:
    EMAIL_ON:
      - DAILY_DRAWDOWN_BREACH
      - TOTAL_RISK_BREACH
